services:
  dotnet-bestelplatform-db:
    container_name: dotnet-bestelplatform-db
    image: mariadb
    ports:
     - 3307:3306
    volumes:
     - ./db/config:/var/lib/mysql
     - ./db/init:/docker-entrypoint-initdb.d
    environment:
     - MARIADB_ROOT_PASSWORD=root
     - MARIADB_DATABASE=bestelplatform
     - TZ=Europe/Brussels
    restart: unless-stopped
  dotnet-bestelplatform-dbadmin:
    container_name: dotnet-bestelplatform-dbadmin
    image: phpmyadmin
    ports:
     - 81:80
    environment:
     - PMA_HOST=dotnet-bestelplatform-db
    depends_on:
     - dotnet-bestelplatform-db
    restart: unless-stopped
  # dotnet-bestelplatform-app:
  #   container_name: dotnet-bestelplatform-app
  #   build:
  #     context: ./bestelplatform
  #   ports:
  #     - 5005:8080
  #   depends_on:
  #     - dotnet-bestelplatform-db
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=server=dotnet-bestelplatform-db;port=3306;uid=root;pwd=root;database=bestelplatformDB
  #   restart: unless-stopped