//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using bestelplatform.Data.bestelplatform;

//#nullable disable

//namespace bestelplatform.Migrations
//{
//    [DbContext(typeof(BestelplatformContext))]
//    [Migration("20260813233909_MaakVeldenNullable")]
//    partial class MaakVeldenNullable
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "10.0.2")
//                .HasAnnotation("Relational:MaxIdentifierLength", 64);

//            modelBuilder.Entity("Roltoewijzing", b =>
//                {
//                    b.Property<int>("GebruikerId")
//                        .HasColumnType("int(11)")
//                        .HasColumnName("gebruiker_id");

//                    b.Property<int>("RolId")
//                        .HasColumnType("int(11)")
//                        .HasColumnName("rol_id");

//                    b.HasKey("GebruikerId", "RolId")
//                        .HasName("PRIMARY");

//                    b.HasIndex(new[] { "RolId" }, "rol_id");

//                    b.ToTable("roltoewijzing", (string)null);
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Bestellijnen", b =>
//                {
//                    b.Property<int>("BestellingId")
//                        .HasColumnType("int(11)")
//                        .HasColumnName("bestelling_id");

//                    b.Property<int>("ProductId")
//                        .HasColumnType("int(11)")
//                        .HasColumnName("product_id");

//                    b.Property<int>("Hoeveelheid")
//                        .HasColumnType("int(11)")
//                        .HasColumnName("hoeveelheid");

//                    b.HasKey("BestellingId", "ProductId")
//                        .HasName("PRIMARY");

//                    b.HasIndex(new[] { "ProductId" }, "product_id");

//                    b.ToTable("bestellijnen", (string)null);
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Bestellingen", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int(11)")
//                        .HasColumnName("id");

//                    b.Property<int?>("GebruikerId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int(11)")
//                        .HasColumnName("gebruiker_id")
//                        .HasDefaultValueSql("'NULL'");

//                    b.Property<string>("Status")
//                        .IsRequired()
//                        .HasColumnType("enum('geplaatst','geserveerd','klaar','geannuleerd')")
//                        .HasColumnName("status");

//                    b.Property<DateTime>("TijdstipBesteld")
//                        .HasColumnType("datetime")
//                        .HasColumnName("tijdstip_besteld");

//                    b.HasKey("Id")
//                        .HasName("PRIMARY");

//                    b.HasIndex(new[] { "GebruikerId" }, "gebruiker_id");

//                    b.ToTable("bestellingen", (string)null);
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Bezoeker", b =>
//                {
//                    b.Property<int>("GebruikerId")
//                        .HasColumnType("int(11)")
//                        .HasColumnName("gebruiker_id");

//                    b.HasKey("GebruikerId")
//                        .HasName("PRIMARY");

//                    b.ToTable("bezoekers", (string)null);
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Gebruiker", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int(11)")
//                        .HasColumnName("id");

//                    b.Property<bool?>("Geactiveerd")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("tinyint(1)")
//                        .HasColumnName("geactiveerd")
//                        .HasDefaultValueSql("'0'");

//                    b.Property<string>("Naam")
//                        .HasMaxLength(255)
//                        .HasColumnType("varchar(255)")
//                        .HasColumnName("naam");

//                    b.Property<string>("UniekeCode")
//                        .IsRequired()
//                        .HasMaxLength(255)
//                        .HasColumnType("varchar(255)")
//                        .HasColumnName("unieke_code");

//                    b.Property<string>("WachtwoordHash")
//                        .HasMaxLength(255)
//                        .HasColumnType("char(255)")
//                        .HasColumnName("wachtwoord_hash")
//                        .IsFixedLength();

//                    b.HasKey("Id")
//                        .HasName("PRIMARY");

//                    b.ToTable("gebruikers", (string)null);
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Medewerker", b =>
//                {
//                    b.Property<int>("GebruikerId")
//                        .HasColumnType("int(11)")
//                        .HasColumnName("gebruiker_id");

//                    b.HasKey("GebruikerId")
//                        .HasName("PRIMARY");

//                    b.ToTable("medewerkers", (string)null);
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Productdetail", b =>
//                {
//                    b.Property<DateTime>("Tijdstip")
//                        .HasColumnType("datetime")
//                        .HasColumnName("tijdstip");

//                    b.Property<int>("ProductId")
//                        .HasColumnType("int(11)")
//                        .HasColumnName("product_id");

//                    b.Property<string>("Naam")
//                        .IsRequired()
//                        .HasMaxLength(255)
//                        .HasColumnType("varchar(255)")
//                        .HasColumnName("naam");

//                    b.Property<float>("Prijs")
//                        .HasColumnType("float")
//                        .HasColumnName("prijs");

//                    b.Property<string>("Producttype")
//                        .IsRequired()
//                        .HasColumnType("enum('frisdrank','alcoholische drank','warme drank','dessert','voorgerecht','hoofdgerecht','versnapering')")
//                        .HasColumnName("producttype");

//                    b.HasKey("Tijdstip", "ProductId")
//                        .HasName("PRIMARY");

//                    b.HasIndex(new[] { "ProductId" }, "product_id")
//                        .HasDatabaseName("product_id1");

//                    b.ToTable("productdetails", (string)null);
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Producten", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int(11)")
//                        .HasColumnName("id");

//                    b.HasKey("Id")
//                        .HasName("PRIMARY");

//                    b.ToTable("producten", (string)null);
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Rollen", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int(11)")
//                        .HasColumnName("id");

//                    b.Property<string>("Naam")
//                        .IsRequired()
//                        .HasMaxLength(255)
//                        .HasColumnType("varchar(255)")
//                        .HasColumnName("naam");

//                    b.HasKey("Id")
//                        .HasName("PRIMARY");

//                    b.ToTable("rollen", (string)null);
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Tafel", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int(11)")
//                        .HasColumnName("id");

//                    b.Property<int>("Nummer")
//                        .HasColumnType("int(11)")
//                        .HasColumnName("nummer");

//                    b.HasKey("Id")
//                        .HasName("PRIMARY");

//                    b.ToTable("tafels", (string)null);
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Tafeltoewijzingen", b =>
//                {
//                    b.Property<int>("GebruikerId")
//                        .HasColumnType("int(11)")
//                        .HasColumnName("gebruiker_id");

//                    b.Property<int>("TafelId")
//                        .HasColumnType("int(11)")
//                        .HasColumnName("tafel_id");

//                    b.Property<DateTime>("TijdstipToegewezen")
//                        .HasColumnType("datetime")
//                        .HasColumnName("tijdstip_toegewezen");

//                    b.HasKey("GebruikerId", "TafelId", "TijdstipToegewezen")
//                        .HasName("PRIMARY");

//                    b.HasIndex(new[] { "TafelId" }, "tafel_id");

//                    b.ToTable("tafeltoewijzingen", (string)null);
//                });

//            modelBuilder.Entity("Roltoewijzing", b =>
//                {
//                    b.HasOne("bestelplatform.Data.bestelplatform.Medewerker", null)
//                        .WithMany()
//                        .HasForeignKey("GebruikerId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired()
//                        .HasConstraintName("roltoewijzing_ibfk_1");

//                    b.HasOne("bestelplatform.Data.bestelplatform.Rollen", null)
//                        .WithMany()
//                        .HasForeignKey("RolId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired()
//                        .HasConstraintName("roltoewijzing_ibfk_2");
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Bestellijnen", b =>
//                {
//                    b.HasOne("bestelplatform.Data.bestelplatform.Bestellingen", "Bestelling")
//                        .WithMany("Bestellijnens")
//                        .HasForeignKey("BestellingId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired()
//                        .HasConstraintName("bestellijnen_ibfk_1");

//                    b.HasOne("bestelplatform.Data.bestelplatform.Producten", "Product")
//                        .WithMany("Bestellijnens")
//                        .HasForeignKey("ProductId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired()
//                        .HasConstraintName("bestellijnen_ibfk_2");

//                    b.Navigation("Bestelling");

//                    b.Navigation("Product");
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Bestellingen", b =>
//                {
//                    b.HasOne("bestelplatform.Data.bestelplatform.Bezoeker", "Gebruiker")
//                        .WithMany("Bestellingens")
//                        .HasForeignKey("GebruikerId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .HasConstraintName("bestellingen_ibfk_1");

//                    b.Navigation("Gebruiker");
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Bezoeker", b =>
//                {
//                    b.HasOne("bestelplatform.Data.bestelplatform.Gebruiker", "Gebruiker")
//                        .WithOne("Bezoeker")
//                        .HasForeignKey("bestelplatform.Data.bestelplatform.Bezoeker", "GebruikerId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired()
//                        .HasConstraintName("bezoekers_ibfk_1");

//                    b.Navigation("Gebruiker");
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Medewerker", b =>
//                {
//                    b.HasOne("bestelplatform.Data.bestelplatform.Gebruiker", "Gebruiker")
//                        .WithOne("Medewerker")
//                        .HasForeignKey("bestelplatform.Data.bestelplatform.Medewerker", "GebruikerId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired()
//                        .HasConstraintName("medewerkers_ibfk_1");

//                    b.Navigation("Gebruiker");
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Productdetail", b =>
//                {
//                    b.HasOne("bestelplatform.Data.bestelplatform.Producten", "Product")
//                        .WithMany("Productdetails")
//                        .HasForeignKey("ProductId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired()
//                        .HasConstraintName("productdetails_ibfk_1");

//                    b.Navigation("Product");
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Tafeltoewijzingen", b =>
//                {
//                    b.HasOne("bestelplatform.Data.bestelplatform.Bezoeker", "Gebruiker")
//                        .WithMany("Tafeltoewijzingens")
//                        .HasForeignKey("GebruikerId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired()
//                        .HasConstraintName("tafeltoewijzingen_ibfk_1");

//                    b.HasOne("bestelplatform.Data.bestelplatform.Tafel", "Tafel")
//                        .WithMany("Tafeltoewijzingens")
//                        .HasForeignKey("TafelId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired()
//                        .HasConstraintName("tafeltoewijzingen_ibfk_2");

//                    b.Navigation("Gebruiker");

//                    b.Navigation("Tafel");
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Bestellingen", b =>
//                {
//                    b.Navigation("Bestellijnens");
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Bezoeker", b =>
//                {
//                    b.Navigation("Bestellingens");

//                    b.Navigation("Tafeltoewijzingens");
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Gebruiker", b =>
//                {
//                    b.Navigation("Bezoeker");

//                    b.Navigation("Medewerker");
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Producten", b =>
//                {
//                    b.Navigation("Bestellijnens");

//                    b.Navigation("Productdetails");
//                });

//            modelBuilder.Entity("bestelplatform.Data.bestelplatform.Tafel", b =>
//                {
//                    b.Navigation("Tafeltoewijzingens");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
